FROM {REGISTRY}/python-base:{default_python_version}-{BUNDLE_VERSION}

{pre_install}

RUN python{default_python_version} -m pip install --no-cache-dir {package} {extra_deps}

{post_install}

CMD {CMD}
